name: flow1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.0'  # Ensure correct indentation here

      - name: Install dependencies
        run: go mod tidy

      - run: |
          echo  "updating main.go file.."
          sed -i "s/Hello, World!/super world:/g" main_test.go

      - name: Run tests
        run: go test ./...
