name: flow1

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      config:
        description: |
          **Configuration in JSON format. Example:**
           ACT = 1;NSW = 2;NT = 3;QLD = 4;SA = 5;TAS = 6;VIC = 7;WA = 8;
          
          {
            "settlementParams": {
              "creditEnquiryId": "",
              "creditAssessmentId": "",
              "dlpAccountNumber": "",
              "loanApplicationId": "",
              "loanId": "its loan facility config id aka ProductPreferences id",
              "loanTermMonths": 360,
              "offsetAccountNumber": "",
              "productMarketingCode": "HLVAR01",
              "settlementAccountNumber": "",
              "settlementId": "",
              "settlementType": 1,
              "trnState": 7,
              "trn": "1613/230"
            },
            "customers": {
              "soleCustomer": {
                "ocvId": 1111111,
                "personaId": ""
              }
            }
          }
        required: true
jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v dump/dump_test.go | tee output.txt

      - name: Archive test output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output.txt

  read:
    runs-on: ubuntu-latest
    needs: dump
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Download dump test output
        uses: actions/download-artifact@v2
        with:
          name: output
          path: ./

      - name: List files in current directory
        run: ls -la

      - name: Run reading dumped file
        run: |
         go test -v read/read_test.go 2>&1 | tee output1.txt
          exit_code=${PIPESTATUS[0]}
          echo "Test exit code: $exit_code"
          cat output1.txt
          if [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi
