name: flow1

on:
  push:
    branches:
      - main

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.0'  # Ensure correct indentation here

      - name: Install dependencies
        run: go mod tidy

      # - run: |
      #     echo  "updating main.go file.."
      #     sed -i "s/Hello, World!/super world:/g" main_test.go
      #     cat main_test.go
          
      - name: Run tests
        run: go test -v dump/dump_test.go | tee output.txt

      - name: archive
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output.txt
  read:
    runs-on: ubuntu-latest
    needs: dump

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.0'  # Ensure correct indentation here

      - name: Install dependencies
        run: go mod tidy

      - name: Download dump test output
        uses: actions/download-artifact@v2
        with:
          name: output
          path: ./  # Downloading to current directory

      - name: List files in current directory
        run: ls -la

      - name: Run reading dumped file
        run: |
          go test -v read/read_test.go 2>&1 | tee output1.txt
          if [  ${PIPESTATUS[0]} -ne 0   ]; then
            echo "Test failed"
          exit 1
          fi
